# Application
spring.application.name=sb-ecom

# H2 Database (for testing)
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

# Local MySQL Database
# spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce

# AWS RDS MySQL Database
spring.datasource.url=jdbc:mysql://myapplication1.c5qyo62oyeks.ap-southeast-1.rds.amazonaws.com:3306/ecommerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# image storage
project.image=images/

# JWT Configuration
spring.app.jwtSecret=${JWT_SECRET}
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom

# Server port (used when deploying to AWS Elastic Beanstalk)
#server.port=5000

# # Frontend URL
frontend.url=http://localhost:5173/
# # Base URL for uploaded images
image.base.url=http://localhost:8080/images

# Stripe Payment
stripe.secret.key=${STRIPE_SECRET_KEY}